apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: saiaryansoma/e-commerce-backend:latest # This will be replaced by Jenkins
          imagePullPolicy: Always # Ensures the latest image is always pulled
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mysql-service" # The name of the MySQL service
            # Add other environment variables (DB_USER, DB_PASSWORD, etc.) here
            # For production, these should come from Kubernetes Secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000